select * from monarchs

--Inner Join using On
SELECT
	PRIME_MINISTERS.COUNTRY,
	PRIME_MINISTERS.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS
	INNER JOIN PRIME_MINISTERS ON PRESIDENTS.COUNTRY = PRIME_MINISTERS.COUNTRY

--Inner Join using Aliased Tables 
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 ON P1.COUNTRY = P2.COUNTRY

--Inner join using USING 
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 USING (COUNTRY)
