select * from monarchs

--Inner Join using On
SELECT
	PRIME_MINISTERS.COUNTRY,
	PRIME_MINISTERS.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS
	INNER JOIN PRIME_MINISTERS ON PRESIDENTS.COUNTRY = PRIME_MINISTERS.COUNTRY

--Inner Join using Aliased Tables 
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 ON P1.COUNTRY = P2.COUNTRY

--Inner join using USING 
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 USING (COUNTRY)



-- Join Example with USING
SELECT p1.country, p1.continent,  
       president, prime_minister 
FROM prime_ministers AS p1 
INNER JOIN presidents AS p2 
USING(country);

--Chained Inner Joins with USING 
SELECT
	P1.COUNTRY,
	P1.CONTINENT,
	PRESIDENT,
	PRIME_MINISTER,
	PM_START
FROM
	PRIME_MINISTERS AS P1
	INNER JOIN PRESIDENTS AS P2 USING (COUNTRY)
	INNER JOIN PRIME_MINISTER_TERMS AS P3 USING (PRIME_MINISTER);